/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void ButtonDown_click(GImageButton source, GEvent event) { //_CODE_:buttonDown:294586:
  println("imgButton1 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:buttonDown:294586:

public void imgButton2_click1(GImageButton source, GEvent event) { //_CODE_:imgButton2:662125:
  println("imgButton2 - GImageButton >> GEvent." + event + " @ " + millis());
} //_CODE_:imgButton2:662125:

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:dropList1:775845:
  println("dropList1 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:dropList1:775845:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Temperature controler");
  currentTemperatureLabel = new GLabel(this, 448, 16, 176, 20);
  currentTemperatureLabel.setText("Current temperature: XX°C");
  currentTemperatureLabel.setTextBold();
  currentTemperatureLabel.setOpaque(true);
  lockedTemeratureLabel = new GLabel(this, 448, 48, 176, 20);
  lockedTemeratureLabel.setText("Locked temperature: xx°C");
  lockedTemeratureLabel.setTextBold();
  lockedTemeratureLabel.setOpaque(true);
  buttonDown = new GImageButton(this, 448, 80, new String[] { "icon-chevron-down.png", "icon-chevron-down-hover.png", "icon-chevron-down-clicked.png" } );
  buttonDown.addEventHandler(this, "ButtonDown_click");
  imgButton2 = new GImageButton(this, 496, 80, new String[] { "icon-chevron-up.png", "icon-chevron-up-hover.png", "icon-chevron-up-clicked.png" } );
  imgButton2.addEventHandler(this, "imgButton2_click1");
  dropList1 = new GDropList(this, 544, 80, 80, 60, 2);
  dropList1.setItems(loadStrings("list_775845"), 0);
  dropList1.addEventHandler(this, "dropList1_click1");
  sensorLabel1 = new GLabel(this, 448, 112, 80, 20);
  sensorLabel1.setText("Sensor 1:");
  sensorLabel1.setTextBold();
  sensorLabel1.setOpaque(true);
  sensorLabel2 = new GLabel(this, 448, 144, 80, 20);
  sensorLabel2.setText("Sensor 2:");
  sensorLabel2.setTextBold();
  sensorLabel2.setOpaque(true);
  sensorLabel3 = new GLabel(this, 448, 176, 80, 20);
  sensorLabel3.setText("Sensor 3:");
  sensorLabel3.setTextBold();
  sensorLabel3.setOpaque(true);
  sensorLabel4 = new GLabel(this, 448, 208, 80, 20);
  sensorLabel4.setText("Sensor 4:");
  sensorLabel4.setTextBold();
  sensorLabel4.setOpaque(true);
  sensorLabel5 = new GLabel(this, 448, 240, 80, 20);
  sensorLabel5.setText("Sensor 5:");
  sensorLabel5.setTextBold();
  sensorLabel5.setOpaque(true);
  sensorLabel6 = new GLabel(this, 448, 272, 80, 20);
  sensorLabel6.setText("Sensor 6:");
  sensorLabel6.setTextBold();
  sensorLabel6.setOpaque(true);
  sensorValue1 = new GLabel(this, 544, 112, 80, 20);
  sensorValue1.setText("xx°C");
  sensorValue1.setTextBold();
  sensorValue1.setOpaque(true);
  sensorLavel2 = new GLabel(this, 544, 144, 80, 20);
  sensorLavel2.setText("xx°C");
  sensorLavel2.setTextBold();
  sensorLavel2.setOpaque(true);
  sensorLavel3 = new GLabel(this, 544, 176, 80, 20);
  sensorLavel3.setText("xx°C");
  sensorLavel3.setTextBold();
  sensorLavel3.setOpaque(true);
  sensorlavel4 = new GLabel(this, 544, 208, 80, 20);
  sensorlavel4.setText("xx°C");
  sensorlavel4.setTextBold();
  sensorlavel4.setOpaque(true);
  sensorLavel5 = new GLabel(this, 544, 240, 80, 20);
  sensorLavel5.setText("xx°C");
  sensorLavel5.setTextBold();
  sensorLavel5.setOpaque(true);
  sensorLavel6 = new GLabel(this, 544, 272, 80, 20);
  sensorLavel6.setText("xx°C");
  sensorLavel6.setTextBold();
  sensorLavel6.setOpaque(true);
}

// Variable declarations 
// autogenerated do not edit
GLabel currentTemperatureLabel; 
GLabel lockedTemeratureLabel; 
GImageButton buttonDown; 
GImageButton imgButton2; 
GDropList dropList1; 
GLabel sensorLabel1; 
GLabel sensorLabel2; 
GLabel sensorLabel3; 
GLabel sensorLabel4; 
GLabel sensorLabel5; 
GLabel sensorLabel6; 
GLabel sensorValue1; 
GLabel sensorLavel2; 
GLabel sensorLavel3; 
GLabel sensorlavel4; 
GLabel sensorLavel5; 
GLabel sensorLavel6; 